- hosts: hosts
  remote_user: root
  tasks:
    - name: 创建/root/local/bin/文件夹
      shell: mkdir -p /root/local/bin

    - name: 下载 docker 二进制文件
      copy: src=/usr/src/docker/bin/{{ item }} dest=/root/local/bin/{{ item }} mode=0755
      with_items:
      - docker-containerd
      - docker-containerd-shim
      - docker-init
      - docker-runc
      - docker
      - docker-containerd-ctr
      - dockerd
      - docker-proxy

    - name: docker命令自动补全
      copy: src=/usr/src/docker/bin/docker dest=/etc/bash_completion.d/docker mode=0644

    - name: docker国内镜像加速
      copy: src=/usr/src/docker/daemon.json dest=/etc/docker/daemon.json

    - name: 创建docker的systemd unit文件
      template: src=/usr/src/docker/docker.service.j2 dest=/etc/systemd/system/docker.service

    - name: 开启docker 服务
      shell: systemctl daemon-reload && systemctl restart docker

    - name: 实现开机自启
      shell: systemctl enable docker